//
//  ListRouter.swift
//  SiberianVIPER
//
//  Created by Sergey Petrachkov on 25/12/2017.
//  Copyright (c) 2017 Sergey Petrachkov. All rights reserved.
//
//  This file was generated by the Actonica VIPER Xcode Templates so
//  you can apply VIPER architecture to your iOS projects
//

import UIKit

protocol ListRoutingLogic {
//  func showSomething(from view: UIViewController, with routingParams : YourRoutingParams)
}


class ListRouter: ListRoutingLogic {
  // MARK: Routing
//  func showSomething(from view: UIViewController, with routingParams : YourRoutingParams) {
//    let nextVC = NextViewController()
//    nextVC.setup(with: routingParams)
//    view.navigationController?.push(nextVC, animated: true)
//  }
}
