//
//  ListEntities.swift
//  SiberianVIPER
//
//  Created by Sergey Petrachkov on 25/12/2017.
//  Copyright (c) 2017 Sergey Petrachkov. All rights reserved.
//
//  This file was generated by the SergeyPetrachkov VIPER Xcode Templates so
//  you can apply VIPER architecture to your iOS projects
//

import UIKit
import SiberianVIPER

enum List {
  // MARK: - Use cases
  enum DataContext {
    struct Request: PaginationRequest {
      var paginationParams: PaginationParameters
      init(skip: Int, take: Int) {
        self.paginationParams = PaginationParameters(skip: skip, take: take)
      }
    }
    struct Response: ModuleResponse  {
      var originalRequest: Request
      
      let items: [ListItemModel]
    }
    class ViewModel: CollectionViewModel {
      var batchSize: Int = 20
      
      var items: [CollectionModel] = []
      
      var changeSet: [CollectionChange] = []
      
      var isBusy: Bool = false
      
      init() {
        
      }
    }
  }
}
