//
//  ListService.swift
//  SiberianVIPER
//
//  Created by Sergey Petrachkov on 25/12/2017.
//  Copyright (c) 2017 Sergey Petrachkov. All rights reserved.
//
//  This file was generated by the SergeyPetrachkov VIPER Xcode Templates so
//  you can apply VIPER architecture to your iOS projects.
//

import UIKit

protocol ListServiceProtocol: class {
  func getItems(request: List.DataContext.Request,
                   success: @escaping ([Item]) -> Void,
                   failure: @escaping (Error) -> Void)
}

class ListService: ListServiceProtocol {
  func getItems(request: List.DataContext.Request,
                success: @escaping ([Item]) -> Void,
                failure: @escaping (Error) -> Void) {
    DispatchQueue.main.asyncAfter(deadline: .now() + 1,
                                  execute: {
                                    success([Item(textContent: String.randomString(length: 16), number: Int(arc4random_uniform(1024))),
                                             Item(textContent: String.randomString(length: 16), number: Int(arc4random_uniform(1024))),
                                             Item(textContent: String.randomString(length: 16), number: Int(arc4random_uniform(1024))),
                                             Item(textContent: String.randomString(length: 16), number: Int(arc4random_uniform(1024))),
                                             Item(textContent: String.randomString(length: 16), number: Int(arc4random_uniform(1024))),
                                             Item(textContent: String.randomString(length: 16), number: Int(arc4random_uniform(1024)))])
    })
  }
}
