//
//  ListService.swift
//  SiberianVIPER
//
//  Created by Sergey Petrachkov on 25/12/2017.
//  Copyright (c) 2017 Sergey Petrachkov. All rights reserved.
//
//  This file was generated by the SergeyPetrachkov VIPER Xcode Templates so
//  you can apply VIPER architecture to your iOS projects.
//

import UIKit

protocol ListServiceProtocol: class {
  func doSomeWork()	
}

class ListService: ListServiceProtocol {
  func doSomeWork() {
  }
}
