//
//  ListEntities.swift
//  SiberianVIPER
//
//  Created by Sergey Petrachkov on 25/12/2017.
//  Copyright (c) 2017 Sergey Petrachkov. All rights reserved.
//
//  This file was generated by the SergeyPetrachkov VIPER Xcode Templates so
//  you can apply VIPER architecture to your iOS projects
//

import UIKit
import SiberianVIPER

enum List {
  // MARK: - Use cases
  enum DataContext {
    struct Request {
      let skip: Int
      let take: Int
    }
    struct Response {
      let originalRequest: Request
      let items: [ListItemModel]
    }
    class ViewModel: CollectionViewModel {
      var batchSize: Int = 20
      
      var items: [CollectionModel] = []
      
      var changeSet: [CollectionChange] = []
      
      var isBusy: Bool = false
      
      init() {
        
      }
    }
  }
}
