//
//  ListInteractor.swift
//  SiberianVIPER
//
//  Created by Sergey Petrachkov on 25/12/2017.
//  Copyright (c) 2017 Sergey Petrachkov. All rights reserved.
//
//  This file was generated by the SergeyPetrachkov VIPER Xcode Templates so
//  you can apply VIPER architecture to your iOS projects
//

import UIKit

protocol ListInteractorInput: class {
  var output : ListInteractorOutput? { get set }
  func requestItems(request: List.DataContext.Request)
}

protocol ListInteractorOutput: class {
  func didReceive(response: List.DataContext.Response)
  func didFail(with error: Error)
}

class ListInteractor: ListInteractorInput {
  let service: ListServiceProtocol = ListService()
  weak var output: ListInteractorOutput?
  
  // MARK: Do something
  func requestItems(request: List.DataContext.Request) {
    self.service.getItems(request: request,
                          success: { items in
                            let models = items.map({ ListItemModel(currentModel: $0) })
                            self.output?.didReceive(response: List.DataContext.Response(originalRequest: request,
                                                                                        items: models))
    },
                          failure: { error in
                            self.output?.didFail(with: error)
    })
  }
}
