//
//  ListInteractor.swift
//  SiberianVIPER
//
//  Created by Sergey Petrachkov on 25/12/2017.
//  Copyright (c) 2017 Sergey Petrachkov. All rights reserved.
//
//  This file was generated by the SergeyPetrachkov VIPER Xcode Templates so
//  you can apply VIPER architecture to your iOS projects
//

import UIKit

protocol ListInteractorInput: class {
  var output : ListInteractorOutput? { get set }
  func doSomething(request: List.DataContext.Request)
}

protocol ListInteractorOutput: class {
  func didReceive(some data : Any)
  func didFail(with error: Error)
}

class ListInteractor: ListInteractorInput {
  let service: ListServiceProtocol = ListService()
  weak var output: ListInteractorOutput?
  
  // MARK: Do something
  func doSomething(request: List.DataContext.Request) {
    self.service.doSomeWork()
  }
}
