//
//  WelcomeService.swift
//  SiberianVIPER
//
//  Created by Sergey Petrachkov on 13/12/2017.
//  Copyright (c) 2017 Sergey Petrachkov. All rights reserved.
//
//  This file was generated by the SergeyPetrachkov VIPER Xcode Templates so
//  you can apply VIPER architecture to your iOS projects.
//

import UIKit

protocol WelcomeServiceProtocol: class {
  func doSomeWork()	
}

class WelcomeService: WelcomeServiceProtocol {
  func doSomeWork() {
  }
}
