//
//  WelcomeRouter.swift
//  SiberianVIPER
//
//  Created by Sergey Petrachkov on 13/12/2017.
//  Copyright (c) 2017 Sergey Petrachkov. All rights reserved.
//
//  This file was generated by the Actonica VIPER Xcode Templates so
//  you can apply VIPER architecture to your iOS projects
//

import UIKit

protocol WelcomeRoutingLogic {
  func openList(from view: UIViewController, routingParams: Welcome.DataContext.ModuleOut)
}


class WelcomeRouter: WelcomeRoutingLogic {
  // MARK: Routing
  func openList(from view: UIViewController, routingParams: Welcome.DataContext.ModuleOut) {
    let controller = ListAssembly.createModule()
    view.navigationController?.pushViewController(controller, animated: true)
  }
}
