//
//  WelcomePresenter.swift
//  SiberianVIPER
//
//  Created by Sergey Petrachkov on 13/12/2017.
//  Copyright (c) 2017 Sergey Petrachkov. All rights reserved.
//
//  This file was generated by the SergeyPetrachkov VIPER Xcode Templates so
//  you can apply VIPER architecture to your iOS projects
//

import UIKit

protocol WelcomePresenterInput: class {
  var view: UIViewController! { get set }
  var output: WelcomePresenterOutput? { get set }
  var router : WelcomeRoutingLogic? { get set }
  var interactor : WelcomeInteractorInput? { get set }
  func presentSomething()
}
protocol WelcomePresenterOutput: class {
  func didChangeState(viewModel : Welcome.DataContext.ViewModel)
}

class WelcomePresenter: WelcomePresenterInput {
  // MARK: - Essentials
  weak var view: UIViewController!
  weak var output : WelcomePresenterOutput?
  var viewModel : Welcome.DataContext.ViewModel? {
    didSet{
      guard let viewModel = self.viewModel else {
        return
        //or do something else like show placeholder
      }
      self.output?.didChangeState(viewModel: viewModel)
    }
  }
  var router : WelcomeRoutingLogic?
  var interactor : WelcomeInteractorInput?
  // MARK: - Initializers
  init() {
    
  }
  deinit {
    print("WelcomePresenter deinit is called")
  }
  // MARK: - Presenter Input
  func presentSomething() {
    // ask router to navigate somewhere or ask interactor for resources... it's up to you
    // like:
    // let requestParams = RequestParams()
    // self.interactor.getSomeData(requestParams: requestParams)
    // or:
    // let routingParams = RoutingParams(firstValue : self.viewModel.firstValue, secondValue: self.viewModel.secondValue)
    // self.router.showNextModule(from: self.view, with: routingParams)
  }
}
extension WelcomePresenter : WelcomeInteractorOutput {
  // MARK: - Interactor output
  func didReceive(some data: Any) {
    // Process it and act accordingly like:
    // self.output?.didChangeState(viewModel : )
  }
  func didFail(with error: Error) {
//    self.router.showError(error: error)
  }
}