//
//  WelcomeAssembly.swift
//  SiberianVIPER
//
//  Created by Sergey Petrachkov on 13/12/2017.
//  Copyright (c) 2017 Sergey Petrachkov. All rights reserved.
//
//  This file was generated by the SergeyPetrachkov VIPER Xcode Templates so
//  you can apply VIPER architecture to your iOS projects
//

import UIKit

class WelcomeAssembly {
  // MARK: - Constants
  fileprivate static let storyboardId = "Main"
  fileprivate static let controllerStoryboardId = "WelcomeNav"
  // MARK: - Public methods
  static func createModule() -> UIViewController {
    if let navController = UIStoryboard(name: storyboardId,
                                        bundle: nil).instantiateViewController(withIdentifier: controllerStoryboardId) as? UINavigationController,
      let controller = navController.topViewController as? WelcomeViewController {
      let presenter = injectPresenter()
      presenter.output = controller
      presenter.view = controller
      controller.presenter = presenter
      return navController
    } else {
      fatalError("Could not create Welcome module!!! Check Welcome assembly")
    }
  }
  // MARK: - Private injections
  fileprivate static func injectPresenter() -> WelcomePresenterInput {
    let presenter = WelcomePresenter()
    let interactor = injectInteractor()
    interactor.output = presenter
    presenter.interactor = interactor
    let router = injectRouter()
    presenter.router = router
    return presenter
  }
  fileprivate static func injectInteractor() -> WelcomeInteractorInput {
    return WelcomeInteractor()
  }
  fileprivate static func injectRouter() -> WelcomeRoutingLogic {
    return WelcomeRouter()
  }
}
